name: Mac

on:
  workflow_call:
    inputs:
      force-debug-assertions:
        required: false
        type: boolean
      wpt-layout:
        required: false
        type: string
      unit-tests:
        required: false
        default: false
        type: boolean
      upload:
        required: false
        default: false
        type: boolean
      github-release-id:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      force-debug-assertions:
        required: false
        type: boolean
      wpt-layout:
        required: false
        type: choice
        options: ["none", "2013", "2020", "all"]
      unit-tests:
        required: false
        default: false
        type: boolean
      upload:
        required: false
        default: false
        type: boolean
  push:
    branches: ["try-mac", "try-wpt-mac", "try-wpt-mac-2020"]

env:
  cargo_profile_option: ${{ inputs.force-debug-assertions && '--profile release-with-debug-assertions' || '--release' }}
  cargo_profile_name: ${{ inputs.force-debug-assertions && 'release-with-debug-assertions' || 'release' }}
  RUST_BACKTRACE: 1
  SHELL: /bin/bash
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"
  CCACHE: "sccache"
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Mac Build
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        if: github.event_name != 'issue_comment'
        with:
          fetch-depth: 2
      # This is necessary to checkout the pull request if this run was triggered
      # via an `issue_comment` action on a pull request.
      - uses: actions/checkout@v3
        if: github.event_name == 'issue_comment'
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head
          fetch-depth: 2
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: Install taplo
        uses: baptiste0928/cargo-install@v2
        with:
          crate: taplo-cli
          locked: true
      - name: Bootstrap
        run: |
          python3 -m pip install --upgrade pip virtualenv
          python3 ./mach bootstrap
          brew install gnu-tar
      - name: Release build (${{ inputs.force-debug-assertions && 'with' || 'without' }} debug assertions)
        run: |
          python3 ./mach build ${cargo_profile_option}
      - name: Smoketest
        run: python3 ./mach smoketest ${cargo_profile_option}
      - name: Script tests
        run: ./mach test-scripts
      - name: Unit tests
        if: ${{ inputs.unit-tests || github.ref_name == 'try-mac' }}
        timeout-minutes: 30 # https://github.com/servo/servo/issues/30275
        run: python3 ./mach test-unit ${cargo_profile_option}
      - name: Build mach package
        run: python3 ./mach package ${cargo_profile_option}
      - name: Run smoketest for mach package
        run: ./etc/ci/macos_package_smoketest.sh target/${cargo_profile_name}/servo-tech-demo.dmg
      - name: Rename build timing
        run: cp -r target/cargo-timings target/cargo-timings-macos
      - name: Archive build timing
        uses: actions/upload-artifact@v3
        with:
          name: cargo-timings
          # Using a wildcard here ensures that the archive includes the path.
          path: target/cargo-timings-*
      - name: Upload artifact for mach package
        uses: actions/upload-artifact@v3
        with:
          name: mac
          path: target/${cargo_profile_name}/servo-tech-demo.dmg
      - name: Upload nightly
        if: ${{ inputs.upload }}
        run: |
          python3 ./mach upload-nightly mac --secret-from-environment \
            --github-release-id ${{ inputs.github-release-id }}
        env:
          S3_UPLOAD_CREDENTIALS: ${{ secrets.S3_UPLOAD_CREDENTIALS }}
          GITHUB_HOMEBREW_TOKEN: ${{ secrets.HOMEBREW_TOKEN }}
          NIGHTLY_REPO_TOKEN: ${{ secrets.NIGHTLY_REPO_TOKEN }}
          NIGHTLY_REPO: ${{ github.repository_owner }}/servo-nightly-builds
      - name: Build package for target
        run: gtar -czf target.tar.gz target/${cargo_profile_name}/servo target/${cargo_profile_name}/*.dylib target/${cargo_profile_name}/lib/*.dylib resources
      - name: Upload package for target
        uses: actions/upload-artifact@v3
        with:
          name: release-binary-macos
          path: target.tar.gz

  wpt-2020:
    if: ${{ github.ref_name == 'try-wpt-mac-2020' || inputs.wpt-layout == '2020' || inputs.wpt-layout == 'all' }}
    name: Mac WPT Tests 2020
    needs: ["build"]
    uses: ./.github/workflows/mac-wpt.yml
    with:
      force-debug-assertions: ${{ inputs.force-debug-assertions }}
      layout: "layout-2020"

  wpt-2013:
    if: ${{ github.ref_name == 'try-wpt-mac' || inputs.wpt-layout == '2013' || inputs.wpt-layout == 'all' }}
    name: Mac WPT Tests 2013
    needs: ["build"]
    uses: ./.github/workflows/mac-wpt.yml
    with:
      force-debug-assertions: ${{ inputs.force-debug-assertions }}
      layout: "layout-2013"

  result:
    name: Result
    runs-on: ubuntu-latest
    if: always()
    # needs all build to detect cancellation
    needs:
      - "build"
      - "wpt-2020"
      - "wpt-2013"

    steps:
      - name: Mark the job as successful
        run: exit 0
        if: ${{ !contains(needs.*.result, 'failure') && !contains(needs.*.result, 'cancelled') }}
      - name: Mark the job as unsuccessful
        run: exit 1
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
